# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.
 
#---------------------------------#
#      general configuration      #
#---------------------------------#
 
# version format
version: 1.0.1.{build}                 # You can use {branch} to, for example
 
# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}
 
# branches to build
branches:
  # whitelist
  only:
    - master
 
# Do not build on tags (GitHub only)
skip_tags: true

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU
 
# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU
 
# build Configuration, i.e. Debug, Release, etc.
configuration: Release
 
# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

# scripts to run before build
before_build:
 
# scripts to run after build
after_build:
 
# to run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: msbuild Source\TestProject.NET40.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: msbuild Source\TestProject.NET45.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
 
# to disable automatic builds
#build: off
 
#---------------------------------#
#       tests configuration       #
#---------------------------------#
 
test:
  assemblies:
    - **\bin\*\Release\TestProject.UnitTests.dll
 
#  categories:
#    - UI
#    - E2E
 
# to run tests from different categories as separate jobs in parallel
#test:
#  categories:
#    - A            # A category common for all jobs
#    - [UI]         # 1st job
#    - [DAL, BL]    # 2nd job
 
# scripts to run before tests
before_test:
#  - echo script1
#  - ps: Write-Host "script1"
 
# scripts to run after tests
after_test:
 
# to run your custom scripts instead of automatic tests
#test_script:
#  - echo This is my custom test script
 
# to disable automatic tests 
#test: off
